spring.application.name=ravik-backend
spring.datasource.url=jdbc:mysql://localhost:3306/ravikdb
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=UTC

jwt.secret=mR+6pPoBja/OWtMjG3qwgUaKsllnemqEI+5ILBo6ZmE=
jwt.expiration=3600000

logging.level.org.springframework.web=DEBUG